[build]
  base = "portfolio"
  publish = "build"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
